accum_grad: 1
allow_variable_data_keys: false
batch_bins: 1000000
batch_size: 20
batch_type: numel
best_model_criterion:
- - valid
  - text2mel_loss
  - min
- - train
  - text2mel_loss
  - min
- - train
  - total_count
  - max
bpemodel: null
chunk_length: 500
chunk_shift_ratio: 0.5
cleaner: null
collect_stats: false
config: conf/train_jets.yaml
create_graph_in_tensorboard: false
cudnn_benchmark: false
cudnn_deterministic: false
cudnn_enabled: true
detect_anomaly: false
dist_backend: nccl
dist_init_method: env://
dist_launcher: null
dist_master_addr: null
dist_master_port: null
dist_rank: null
dist_world_size: null
distributed: false
dry_run: false
early_stopping_criterion:
- valid
- loss
- min
energy_extract: energy
energy_extract_conf:
  fs: 22050
  hop_length: 256
  n_fft: 1024
  reduction_factor: 1
  use_token_averaged_energy: false
  win_length: null
energy_normalize: global_mvn
energy_normalize_conf:
  stats_file: /home/hainh/miniconda3/envs/espnet/lib/python3.9/site-packages/espnet_model_zoo/5e3421ca07451a3bb7abce609bd03691/exp_lantrinh/tts_stats_raw_char/train/energy_stats.npz
feats_extract: fbank
feats_extract_conf:
  fmax: 7600
  fmin: 80
  fs: 22050
  hop_length: 256
  n_fft: 1024
  n_mels: 80
  win_length: null
fold_length:
- 150
- 204800
freeze_param: []
g2p: null
generator_first: true
grad_clip: -1
grad_clip_type: 2.0
grad_noise: false
hop_length: 256
ignore_init_mismatch: false
init_param: []
iterator_type: sequence
keep_nbest_models: 5
local_rank: 0
log_interval: 50
log_level: INFO
max_cache_fd: 32
max_cache_size: 0.0
max_epoch: 600
model_conf: {}
multiple_iterator: false
multiprocessing_distributed: false
nbest_averaging_interval: 0
ngpu: 1
no_forward_run: false
non_linguistic_symbols: null
normalize: global_mvn
normalize_conf:
  stats_file: /home/hainh/miniconda3/envs/espnet/lib/python3.9/site-packages/espnet_model_zoo/5e3421ca07451a3bb7abce609bd03691/exp_lantrinh/tts_stats_raw_char/train/feats_stats.npz
num_att_plot: 3
num_cache_chunks: 1024
num_iters_per_epoch: 1000
num_workers: 4
odim: null
optim: adamw
optim2: adamw
optim2_conf:
  betas:
  - 0.8
  - 0.99
  eps: 1.0e-09
  lr: 0.0002
  weight_decay: 0.0
optim_conf:
  betas:
  - 0.8
  - 0.99
  eps: 1.0e-09
  lr: 0.0002
  weight_decay: 0.0
output_dir: exp_lantrinh/tts_train_jets_raw_char
patience: null
pitch_extract: dio
pitch_extract_conf:
  f0max: 400
  f0min: 80
  fs: 22050
  hop_length: 256
  n_fft: 1024
  reduction_factor: 1
  use_token_averaged_f0: false
pitch_normalize: global_mvn
pitch_normalize_conf:
  stats_file: /home/hainh/miniconda3/envs/espnet/lib/python3.9/site-packages/espnet_model_zoo/5e3421ca07451a3bb7abce609bd03691/exp_lantrinh/tts_stats_raw_char/train/pitch_stats.npz
pretrain_path: null
print_config: false
required:
- output_dir
- token_list
resume: true
sample_rate: 22050
scheduler: exponentiallr
scheduler2: exponentiallr
scheduler2_conf:
  gamma: 0.999875
scheduler_conf:
  gamma: 0.999875
seed: 777
sharded_ddp: false
sort_batch: descending
sort_in_batch: descending
token_list:
- <space>
- <unk>
- '#'
- '1'
- a
- '-'
- t
- X
- '9'
- '2'
- k
- m
- n
- N
- i
- '5'
- j
- o
- e
- w
- M
- d
- h
- '3'
- '7'
- '6'
- p
- J
- u
- S
- O
- '8'
- s
- E
- l
- v
- b
- '4'
- x
- z
- f
- r
- Z
- G
- <sos/eos>
token_type: char
train_data_path_and_name_and_type:
- - dump/raw/tr_no_dev/text
  - text
  - text
- - dump/raw/tr_no_dev/wav.scp
  - speech
  - sound
- - exp_lantrinh/tts_stats_raw_char/train/collect_feats/pitch.scp
  - pitch
  - npy
- - exp_lantrinh/tts_stats_raw_char/train/collect_feats/energy.scp
  - energy
  - npy
train_dtype: float32
train_shape_file:
- exp_lantrinh/tts_stats_raw_char/train/text_shape.char
- exp_lantrinh/tts_stats_raw_char/train/speech_shape
tts: jets
tts_conf:
  cache_generator_outputs: true
  discriminator_adv_loss_params:
    average_by_discriminators: false
    loss_type: mse
  discriminator_params:
    follow_official_norm: false
    period_discriminator_params:
      bias: true
      channels: 32
      downsample_scales:
      - 3
      - 3
      - 3
      - 3
      - 1
      in_channels: 1
      kernel_sizes:
      - 5
      - 3
      max_downsample_channels: 1024
      nonlinear_activation: LeakyReLU
      nonlinear_activation_params:
        negative_slope: 0.1
      out_channels: 1
      use_spectral_norm: false
      use_weight_norm: true
    periods:
    - 2
    - 3
    - 5
    - 7
    - 11
    scale_discriminator_params:
      bias: true
      channels: 128
      downsample_scales:
      - 2
      - 2
      - 4
      - 4
      - 1
      in_channels: 1
      kernel_sizes:
      - 15
      - 41
      - 5
      - 3
      max_downsample_channels: 1024
      max_groups: 16
      nonlinear_activation: LeakyReLU
      nonlinear_activation_params:
        negative_slope: 0.1
      out_channels: 1
      use_spectral_norm: false
      use_weight_norm: true
    scale_downsample_pooling: AvgPool1d
    scale_downsample_pooling_params:
      kernel_size: 4
      padding: 2
      stride: 2
    scales: 1
  discriminator_type: hifigan_multi_scale_multi_period_discriminator
  feat_match_loss_params:
    average_by_discriminators: false
    average_by_layers: false
    include_final_outputs: true
  generator_adv_loss_params:
    average_by_discriminators: false
    loss_type: mse
  generator_params:
    adim: 256
    aheads: 2
    conformer_activation_type: swish
    conformer_dec_kernel_size: 31
    conformer_enc_kernel_size: 7
    conformer_pos_enc_layer_type: rel_pos
    conformer_rel_pos_type: latest
    conformer_self_attn_layer_type: rel_selfattn
    decoder_normalize_before: true
    decoder_type: transformer
    dlayers: 4
    dunits: 1024
    duration_predictor_chans: 256
    duration_predictor_kernel_size: 3
    duration_predictor_layers: 2
    elayers: 4
    encoder_normalize_before: true
    encoder_type: transformer
    energy_embed_dropout: 0.0
    energy_embed_kernel_size: 1
    energy_predictor_chans: 256
    energy_predictor_dropout: 0.5
    energy_predictor_kernel_size: 3
    energy_predictor_layers: 2
    eunits: 1024
    generator_bias: true
    generator_channels: 256
    generator_global_channels: -1
    generator_kernel_size: 7
    generator_nonlinear_activation: LeakyReLU
    generator_nonlinear_activation_params:
      negative_slope: 0.1
    generator_out_channels: 1
    generator_resblock_dilations:
    - - 1
      - 3
      - 5
    - - 1
      - 3
      - 5
    - - 1
      - 3
      - 5
    generator_resblock_kernel_sizes:
    - 3
    - 7
    - 11
    generator_upsample_kernel_sizes:
    - 16
    - 16
    - 4
    - 4
    generator_upsample_scales:
    - 8
    - 8
    - 2
    - 2
    generator_use_additional_convs: true
    generator_use_weight_norm: true
    idim: 45
    init_type: xavier_uniform
    odim: 80
    pitch_embed_dropout: 0.0
    pitch_embed_kernel_size: 1
    pitch_predictor_chans: 256
    pitch_predictor_dropout: 0.5
    pitch_predictor_kernel_size: 5
    pitch_predictor_layers: 5
    positionwise_conv_kernel_size: 3
    positionwise_layer_type: conv1d
    segment_size: 64
    stop_gradient_from_energy_predictor: false
    stop_gradient_from_pitch_predictor: true
    transformer_dec_attn_dropout_rate: 0.2
    transformer_dec_dropout_rate: 0.2
    transformer_dec_positional_dropout_rate: 0.2
    transformer_enc_attn_dropout_rate: 0.2
    transformer_enc_dropout_rate: 0.2
    transformer_enc_positional_dropout_rate: 0.2
    use_cnn_in_conformer: true
    use_macaron_style_in_conformer: true
    use_masking: true
  generator_type: jets_generator
  lambda_adv: 1.0
  lambda_align: 2.0
  lambda_feat_match: 2.0
  lambda_mel: 45.0
  lambda_var: 1.0
  mel_loss_params:
    fmax: null
    fmin: 0
    fs: 22050
    hop_length: 256
    log_base: null
    n_fft: 1024
    n_mels: 80
    win_length: null
    window: hann
  sampling_rate: 22050
tts_model:
  model_path: ../jets_weights/lantrinh_v2_22k/full/jets.onnx
  model_type: JETS
unused_parameters: true
use_amp: false
use_matplotlib: true
use_preprocessor: true
use_tensorboard: true
use_wandb: false
val_scheduler_criterion:
- valid
- loss
valid_batch_bins: null
valid_batch_size: null
valid_batch_type: null
valid_data_path_and_name_and_type:
- - dump/raw/dev/text
  - text
  - text
- - dump/raw/dev/wav.scp
  - speech
  - sound
- - exp_lantrinh/tts_stats_raw_char/valid/collect_feats/pitch.scp
  - pitch
  - npy
- - exp_lantrinh/tts_stats_raw_char/valid/collect_feats/energy.scp
  - energy
  - npy
valid_max_cache_size: null
valid_shape_file:
- exp_lantrinh/tts_stats_raw_char/valid/text_shape.char
- exp_lantrinh/tts_stats_raw_char/valid/speech_shape
version: '202209'
vocoder:
  vocoder_type: not_used
wandb_entity: null
wandb_id: null
wandb_model_log_interval: -1
wandb_name: null
wandb_project: null
write_collected_feats: false
